# Generated by Django 6.0 on 2026-01-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=200)),
                ('meeting_name', models.CharField(max_length=200)),
                ('bookmaker', models.CharField(max_length=50)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('NZ', 'New Zealand')], default='AU', max_length=2)),
                ('meeting_type', models.CharField(choices=[('gallops', 'Gallops'), ('harness', 'Harness')], max_length=20)),
                ('date', models.DateField()),
                ('total_races', models.PositiveIntegerField(default=0)),
                ('completed_races', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('participant_type', models.CharField(choices=[('jockey', 'Jockey'), ('driver', 'Driver')], max_length=20)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('total_wins', models.PositiveIntegerField(default=0)),
                ('win_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('completed_rides', models.PositiveIntegerField(default=0)),
                ('remaining_rides', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('ai_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='racing.meeting')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='racing.participant')),
            ],
            options={
                'ordering': ['-points', 'ai_price'],
                'unique_together': {('meeting', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='BookmakerOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(choices=[('tab', 'TAB'), ('ladbrokes', 'Ladbrokes'), ('sportsbet', 'Sportsbet'), ('tabtouch', 'TABtouch'), ('pointsbet', 'PointsBet')], max_length=20)),
                ('win_odds', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='racing.challengeentry')),
            ],
            options={
                'unique_together': {('challenge_entry', 'bookmaker')},
            },
        ),
    ]
