# Generated by Django 6.0 on 2026-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFetchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('meeting_type', models.CharField(max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('fetch_interval_seconds', models.IntegerField(default=60)),
                ('last_fetch_at', models.DateTimeField(blank=True, null=True)),
                ('last_race_fetched', models.IntegerField(default=0)),
                ('total_races', models.IntegerField(default=8)),
                ('jockeys_list', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auto Fetch Config',
                'verbose_name_plural': 'Auto Fetch Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global State',
                'verbose_name_plural': 'Global States',
            },
        ),
        migrations.CreateModel(
            name='LiveTrackerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('meeting_type', models.CharField(max_length=20)),
                ('margin', models.FloatField(default=1.3)),
                ('total_races', models.IntegerField(default=8)),
                ('races_completed', models.IntegerField(default=0)),
                ('participants_data', models.TextField()),
                ('race_results_data', models.TextField(default='[]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Tracker',
                'verbose_name_plural': 'Live Trackers',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='meetingodds',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.CharField(db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='country',
            field=models.CharField(db_index=True, default='AU', max_length=5),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingodds',
            name='bookmaker',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingodds',
            name='participant_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingodds',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('meeting', 'name')},
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(db_index=True, max_length=100)),
                ('meeting_date', models.DateField(db_index=True)),
                ('participant_name', models.CharField(db_index=True, max_length=100)),
                ('participant_type', models.CharField(max_length=20)),
                ('bookmaker', models.CharField(db_index=True, max_length=50)),
                ('odds', models.FloatField()),
                ('ai_price', models.FloatField(blank=True, null=True)),
                ('is_value', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['meeting_name', 'meeting_date'], name='racing_odds_meeting_127114_idx'), models.Index(fields=['participant_name', 'meeting_date'], name='racing_odds_partici_3b18cc_idx'), models.Index(fields=['bookmaker', 'captured_at'], name='racing_odds_bookmak_d76149_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(db_index=True, max_length=100)),
                ('meeting_date', models.DateField(db_index=True)),
                ('participant_name', models.CharField(db_index=True, max_length=100)),
                ('participant_type', models.CharField(max_length=20)),
                ('race_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('points_earned', models.FloatField()),
                ('is_dead_heat', models.BooleanField(default=False)),
                ('dead_heat_with', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Points Ledger Entry',
                'verbose_name_plural': 'Points Ledger',
                'ordering': ['meeting_name', 'race_number', 'position'],
                'indexes': [models.Index(fields=['meeting_name', 'meeting_date'], name='racing_poin_meeting_8edf40_idx'), models.Index(fields=['participant_name', 'meeting_date'], name='racing_poin_partici_9a29ce_idx')],
                'unique_together': {('meeting_name', 'meeting_date', 'participant_name', 'race_number')},
            },
        ),
    ]
